
services:

  server-web:
    build: ./front_end/mememuseum
    container_name: meme_server_web
    ports:
      - "443:443"
      - "80:80"
    networks:
      - meme-museum
    tty: true
    stdin_open: true


  node-app:
    build: ./back_end
    container_name: meme_node
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - meme-museum
    tty: true
    stdin_open: true
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: meme_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"              
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
      - meme-museum
    
  postgresql:
    image: postgres:15
    container_name: meme_db
    environment:
      POSTGRES_USER: db     
      POSTGRES_PASSWORD: db  
      POSTGRES_DB: meme_database             # contiene POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - meme-museum
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username db --dbname meme_database"]
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  meme-museum:
    driver: bridge

volumes:
  pgadmin_data:
  postgres_data:

